### PR TITLE
LRIS-31773

### PR DESCRIPTION
**Pull request by rdai10**
https://issues.liferay.com/browse/LRIS-31773

### CODE REVIEW

**Comment by rdai10** [comment]
resolved merge conflict

**Comment by jonmak08** [comment]
Reviewed and Merged.  Thanks!

**Comment by jonmak08** [comment]
Looks like you made changes after I pulled.  Reviewing again.

**Comment by rdai10** [comment]
Sorry~ :bowing_woman:

**Comment by jonmak08** [comment]
Reviewed and Merged.  Thanks!

**Comment by jonmak08** [comment]
No worries.  I just didnt realize you force pushed something since I already pulled it and was reviewing.

**Comment by rdai10** [comment]
Thanks, sorry about that :bowing_woman:

**Pull request closed without merging**
